# Generated by Django 4.2 on 2023-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
    ]
