# Generated by Django 4.2 on 2024-01-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
    ]
