# Generated by Django 4.2 on 2024-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_delete_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
