# Generated by Django 4.2 on 2024-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_form_email_alter_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
