# Generated by Django 4.2 on 2024-03-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_downloadcv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcv',
            old_name='file',
            new_name='files',
        ),
    ]
