# Generated by Django 4.2 on 2024-03-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_rename_file_downloadcv_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadcv',
            old_name='files',
            new_name='file',
        ),
    ]
