# Generated by Django 4.2 on 2024-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0008_rename_downloadcv_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
